### ISSUE TITLE
Update build to not include node_modules

### ISSUE THREAD

**Issue by Eranziel** [eronth/bunkers-and-badasses#79]
Hi there! I'm one of the developers for the Forge, and we've received reports that users are unable to use this system on our service. I investigated and found it is because the package includes files in `node_modules` which are required by `system.json`. Those files aren't present for Forge users (see below).

As part of the Forge's optimizations for its users, it skips a few folders when unzipping packages. These include `.git`, `node_modules`, and a few others. We've found that in 99% of cases these folders are included by accident, and unzipping the (usually) hundreds or thousands of files in those folders would just end up wasting time and/or space. Your case of only having a single node dependency is very rare!

As an aside for additional context, the `node_modules` folder is intended by Node to only be used for local or server-side Node apps, not to be served as browser-side content. For Foundry systems & modules, devs should use a build script or tool to generate their packages. Typically this involves copying/compiling files to an output directory which is then zipped for distribution. Also note that committing the `node_modules` folder to Git is very atypical! Committing `package.json` and `package-lock.json` will allow a new dev environment to get set up quickly with a simple `npm install` command.

I see you're already using Gulp, so it should be relatively straightforward to create a gulp task which copies the relevant files to a `dist` or `lib` folder or similar for packaging. If you have any questions or need any additional guidance on this please let me know!

**Comment by eronth** [comment]
I ended up simply removing the module for now. It's not largely being used, so removal was simplest until I actually need it more concretely.

**Comment by eronth** [comment]
Apparently this issue is not yet properly fixed. I'll need to get more details on what is still broken.

**Comment by eronth** [comment]
@Eranziel I have reached out to a user who previously experienced this issue. According to them, they still experience the problem (or something similar) even after my removal of node_modules. Is there any way you could check into what's happening for me? I currently do not have an account with Forge to fiddle around with deployment.

**Comment by Eranziel** [comment]
@eronth the version on the Forge is still 0.4.4, which is why it's still an issue. Looks like your 0.4.5 zip still has the 0.4.4 `system.json` in it, which is why Forge isn't updating. The Forge updater is seeing the new version on Foundry's listing, downloading the zip, then looking at the version in `system.json` and seeing it hasn't changed, so then doesn't add the new version to our database.

A couple other suggestions for your `system.json` that might save you some work. If you make the manifest URL `https://github.com/eronth/bunkers-and-badasses/releases/latest/download/system.json` you don't need to update it each release - it will always point to the latest version. You can also upload your packaged zip to the release instead of pushing it to git to keep the size of your repo smaller over time, since git doesn't handle diffs of binary files as well.

**Comment by eronth** [comment]
I had misunderstood how creating a release worked. I have removed and re-created the tag. I'll update the manifest with my next major update (probably).
