### ISSUE TITLE
Unable to Install Game System on Foundry VTT Version 11 Build 301

### ISSUE THREAD

**Issue by B4ND1T-TP** [eronth/bunkers-and-badasses#81]
When Trying to install the game system on Foundry VTT, I get the following error "Error: Unable to load valid system manifest data from "https://github.com/eronth/bunkers-and-badasses/releases/download/v0.4.5/system.json" System validation errors: packs: 0: type: may not be undefined 1: type: may not be undefined 2: type: may not be undefined 3: type: may not be undefined 4: type: may not be undefined"
![FTTVBNBError](https://github.com/eronth/bunkers-and-badasses/assets/99439293/2af50da7-34a8-479f-b2f5-8f49276859b8)

**Comment by eronth** [comment]
I'm not seeing this issue on version 10. When I have a bit more time I'll check against Version 11, which I suspect is the culprit.

**Comment by Eschguy** [comment]
Issue persists on build 302

**Comment by eronth** [comment]
This should be fixed with the latest version of B&B (v0.4.6) now. You might need to uninstall the system before re-installing, but your data should remain. The safest option is, as always, back your data up.

**Comment by Eschguy** [comment]
Works on a fresh v11 install!
